development:
  adapter: mysql
  encoding: utf8
  database: <project>_dev
  username: root
  password: <password>
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: <project>_test
  username: root
  password: <password>
  host: localhost